version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    ignore:
      update-types: ["version-update:semver-patch"]
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    ignore:
      update-types: ["version-update:semver-patch"]
    schedule:
      interval: "weekly"
